### ISSUE TITLE
Questions about the ratio of postive and negative samples

### ISSUE THREAD

**Issue by zxhr2793** [ChiCheng123/SRN#2]
If the input size is set to 1024*1024, the backbone is ResNet50 with 6-level pyramid and 2 anchors at each point of each level, the total anchors should be (256*256+128*128+64*64+32*32+16*16+8*8)*2=174712, even sum up the anchors at P_i level, the result is 174712*2=349424. This result is not equal to the anchors reported in Figure 1 (a) (339700+22=339722).

Therefore, is my calcutation wrong? How do you analyze the ratio of positive and negative and obtain the reported figure?

**Comment by ChiCheng123** [comment]
Figure 1(a) shows the statistical average of each mini-batch, which includes 2 images per GPU. And 339700 and 22 are the statistical average, their sum may be not exactly equal to the total number of anchors.

**Comment by zxhr2793** [comment]
> Figure 1(a) shows the statistical average of each mini-batch, which includes 2 images per GPU. And 339700 and 22 are the statistical average, their sum may be not exactly equal to the total number of anchors.

Thanks for your response. My calculation is wrong. Some anchors are ignored during training for their overlaps lying in the ignorable interval.
