### ISSUE TITLE
about paper

### ISSUE THREAD

**Issue by foralliance** [ChiCheng123/SRN#6]
在paper中，对于AFW和PASCAL这2个数据集，在各自的Figure中，有 **STN**，**Faceness**，**NPD**这3项．

可是在现有的测试曲线代码中，貌似并没有这3个的结果．请问您是手动添加的还是？？

麻烦了！

**Comment by sfzhang15** [comment]
@foralliance 
你好，这三个结果是向作者要了检测结果文件，然后添加进去的。
