### ISSUE TITLE
about GPU

### ISSUE THREAD

**Issue by foralliance** [ChiCheng123/SRN#7]
对于测试过程，如果想增加输入尺寸，就需要增大GPU的显存．
这种一幅幅图片的测试过程，是不是无法使用GPU并行的方案．**换句话说：**对于测试过程，只能用单卡，想要增大GPU的显存，只能增大单张显卡的显存，如1080TI(11G)换P40(24G)或更好的显卡．测试是没法通过GPU并行来增大显存的．
这样的理解对吗？麻烦了！！

**Comment by ChiCheng123** [comment]
> 对于测试过程，如果想增加输入尺寸，就需要增大GPU的显存．
> 这种一幅幅图片的测试过程，是不是无法使用GPU并行的方案．**换句话说：**对于测试过程，只能用单卡，想要增大GPU的显存，只能增大单张显卡的显存，如1080TI(11G)换P40(24G)或更好的显卡．测试是没法通过GPU并行来增大显存的．
> 这样的理解对吗？麻烦了！！

目前是这样的。可以尝试把一张图裁成几张小图分别测，不过要注意边界上的检测结果。
