### ISSUE TITLE
关于Two-step classification

### ISSUE THREAD

**Issue by li3cmz** [ChiCheng123/SRN#8]
你好，通过阅读您的模型代码和论文，我没有发现关于论文里面提到的如下陈述的相关代码实现：the ﬁrst step ﬁlters out most simple negative anchors using a preset negative threshold θ = 0.99 to reduce the search space for the subsequent step. 
阅读您的模型代码可以发现： (c2_r, c3_r, c4_r, c5_r, c6_r, c7_r), (p2, p3, p4, p5, p6, p7) 是您提取出来的特征，那么论文Figure 2中的anchor filter具体实现是如何做到的吗？是在哪一步去实现它的呢？

期待您的回复! 感激

**Comment by ChiCheng123** [comment]
[https://github.com/ChiCheng123/SRN/blob/master/srn/model/rpn_proposal.py#L50-L56](url)

**Comment by ChiCheng123** [comment]
https://github.com/ChiCheng123/SRN/blob/fc07d7499bb5d8291cec68124fc50879f2f68147/srn/model/rpn_proposal.py#L50-L56

**Comment by li3cmz** [comment]
了解！谢谢辣~
